=== 2lambda123/magento-magento2/app/code/Magento/PageBuilder/etc/content_types.xsd
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="groups">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="group" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="label"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                    <xs:attribute type="xs:string" name="translate" use="optional"/>
                                    <xs:attribute type="xs:byte" name="sortOrder" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="content_types">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element type="xs:string" name="label"/>
                                        <xs:element type="xs:string" name="icon"/>
                                        <xs:element type="xs:string" name="component" minOccurs="0"/>
                                        <xs:element type="xs:string" name="preview_template" minOccurs="0"/>
                                        <xs:element type="xs:string" name="render_template" minOccurs="0"/>
                                        <xs:element type="xs:string" name="preview_component" minOccurs="0"/>
                                        <xs:element type="xs:string" name="backend_block" minOccurs="0"/>
                                        <xs:element type="xs:string" name="backend_template" minOccurs="0"/>
                                        <xs:element type="xs:string" name="form"/>
                                        <xs:element type="xs:string" name="group"/>
                                        <xs:element type="xs:string" name="allowed_parents" minOccurs="0"/>
                                        <xs:element type="readers" name="readers" minOccurs="1"/>
                                        <xs:element name="appearances" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="appearance" name="appearance" minOccurs="1" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="is_visible" minOccurs="0"/>
                                    </xs:all>
                                    <xs:attribute type="xs:string" name="name" use="required"/>
                                    <xs:attribute type="xs:string" name="translate" use="required"/>
                                    <xs:attribute type="xs:byte" name="sortOrder" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="appearance">
        <xs:sequence>
            <xs:element name="data" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:string" name="preview_template" minOccurs="0"/>
            <xs:element type="xs:string" name="render_template" minOccurs="0"/>
            <xs:element type="readers" name="readers" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="readers">
        <xs:sequence>
            <xs:element type="reader" name="reader" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="reader">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="component" use="required"/>
    </xs:complexType>
</xs:schema>

=== 2lambda123/magento-magento2/app/code/Magento/PageBuilder/etc/content_types/column_group.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_types.xsd">
    <content_types>
        <type name="column-group" sortOrder="10" translate="label">
            <label>Column Group</label>
            <icon>icon-pagebuilder-column</icon>
            <form/>
            <group>general</group>
            <component>Magento_PageBuilder/js/component/block/column-group</component>
            <preview_component>Magento_PageBuilder/js/component/block/preview/column-group</preview_component>
            <allowed_parents>
                <parent name="row"/>
            </allowed_parents>
            <is_visible>false</is_visible>
            <appearances>
                <appearance default="true" name="default">
                    <preview_template>Magento_PageBuilder/component/block/preview/column-group.html</preview_template>
                    <render_template>Magento_PageBuilder/component/block/render/column-group.html</render_template>
                    <readers>
                        <reader component="Magento_PageBuilder/js/component/format/read/default" name="default"/>
                    </readers>
                </appearance>
            </appearances>
        </type>
    </content_types>
</config>

=== 2lambda123/magento-magento2/app/code/Magento/PageBuilder/etc/content_types/accordion.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_types.xsd">
    <content_types>
        <type name="accordion" sortOrder="10" translate="label">
            <label>Accordion</label>
            <icon>icon-pagebuilder-accordian</icon>
            <component>Magento_PageBuilder/js/content-type-collection</component>
            <preview_component>Magento_PageBuilder/js/content-type/accordion/preview</preview_component>
            <content_component>Magento_PageBuilder/js/content-type/accordion/content</content_component>
            <form>pagebuilder_accordion_form</form>
            <group>interactive</group>
            <allowed_parents>
                <parent name="row"/>
                <parent name="column"/>
                <parent name="tab-item"/>
            </allowed_parents>
            <appearances>
                <appearance default="true" name="default">
                    <preview_template>Magento_PageBuilder/content-type/accordion/default/preview</preview_template>
                    <render_template>Magento_PageBuilder/content-type/accordion/default/master</render_template>
                    <readers>
                        <reader component="Magento_PageBuilder/js/component/format/read/default" name="default"/>
                        <reader component="Magento_PageBuilder/js/component/format/read/accordion" name="accordion"/>
                    </readers>
                </appearance>
            </appearances>
        </type>
    </content_types>
</config>

=== 2lambda123/magento-magento2/app/code/Magento/PageBuilder/etc/content_types/button_item.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_PageBuilder:etc/content_types.xsd">
    <content_types>
        <type name="button-item" translate="label">
            <label>Button</label>
            <icon>icon-pagebuilder-button</icon>
            <component>Magento_PageBuilder/js/content-type-collection</component>
            <preview_component>Magento_PageBuilder/js/component/block/preview/button-item</preview_component>
            <content_component>Magento_PageBuilder/js/component/content/button-item</content_component>
            <form>pagebuilder_button_item_form</form>
            <group>general</group>
            <allowed_parents>
                <parent name="buttons"/>
            </allowed_parents>
            <is_visible>false</is_visible>
            <appearances>
                <appearance default="true" name="default">
                    <preview_template>Magento_PageBuilder/component/block/preview/button-item.html</preview_template>
                    <render_template>Magento_PageBuilder/component/block/render/button-item.html</render_template>
                    <readers>
                        <reader component="Magento_PageBuilder/js/component/format/read/default" name="default"/>
                        <reader component="Magento_PageBuilder/js/component/format/read/button-item" name="button-item"/>
                    </readers>
                </appearance>
            </appearances>
        </type>
    </content_types>
</config>
